version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: _docker/app/Dockerfile
    image: laravel-app
    container_name: laravel-app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - .:/var/www
      - ./_docker/app/php.ini:/usr/local/etc/php/conf.d/local.ini
    ports:
      - "9000:9000"
    depends_on:
      - db

  webserver:
    image: nginx:alpine
    container_name: nginx
    restart: unless-stopped
    ports:
      - "8876:80"
    volumes:
      - .:/var/www
      - ./_docker/nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - app

  db:
    image: mysql:8.0
    container_name: mysql
    restart: always
    ports:
      - "8101:3306"
    environment:
      MYSQL_DATABASE: guest_service
      MYSQL_ROOT_PASSWORD: root
    #   MYSQL_USER: root
      MYSQL_PASSWORD: root
    volumes:
      - ./dbdata/db:/var/lib/mysql
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci


volumes:
  dbdata:
    driver: local

networks:
  app-network:
    driver: bridge
